### PR TITLE
Go arrow

### PR DESCRIPTION
**Pull request by alanconway**

### CODE REVIEW

**Comment by ssorj** [comment]
I ran into trouble (perhaps two different kinds?) when I tested this.  It looks like it could be a result of my having an older version of Go.

https://gist.github.com/ssorj/0ec7f3cc562b4e279d220b8eb15a366d

**Comment by alanconway** [comment]
Thanks, I'll check it out.

I only tested peer-to-peer, I'll try with the brokers and see if I can
reproduce. What Go version were you using? My first feeling is it's a Go
binding bug or interop problem but if I can't reproduce I'll try your
version.

`quiver-arrow-qpid-electron-go: Unexpected delivery outcome: {released
<nil> <nil>}` - a delivery was released by the router, need to find out
why. The router can drop and release pre-settled messages if they can't be
forwarded within is buffering capacity. The Go client is setting
AtLeastOnce but maybe that is not implemented correctly. Note C++ and
python arrows do not check for non-accept outcomes, they should to catch
unexpected behaviour early. C++ does not explictly set at-least-once, but I
think it is the default. If the router releases messages during C++ or
python runs the only way to detect it would be the receiver hanging at the
end of the run because of missing messages, which is late and hard to debug.

`panic: interface conversion: interface {} is nil, not time.Time` - this
looks like the timestamp map entry is missing or NULL, is it possible some
messages are missing that?

`panic: (**amqp.UnmarshalError) (0x5381e0,0x838f18)` - this is at least an
error handling bug - we should not panic with a **, should be *. That's
hiding the error message.

**Comment by alanconway** [comment]
Let me know how things work with these fixes, check the comments on the "Fix interop problems" commit for details. With these fixes I was able to run go against c, cpp and python via dispatch with no problems.

**Comment by alanconway** [comment]
This version of the Go passes the interop tests using the current master electron libraries, so should be ready to merge after 0.27 release. It does not work properly with the 0.26 release to to bugs in the electron library.

**Comment by alanconway** [comment]
Closing stale PRs, re-open if this is a mistake.

**Pull request closed without merging**
